import type { Metadata } from "next";
import { Inter, Lexend } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { inter } from "./fonts";
import Form from "@/components/Form";
import Footer from "@/components/Footer";
import {Providers} from '@/redux/provider'

export const metadata: Metadata = {
  title: "RTS",
  description: "Generated by create next app",
};
  
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="es">
        <body className={`${inter.className} bg-zinc-100`}>
          <Providers>

            <Navbar/>
            {children}
            <Form/>
            <Footer/>
          
          </Providers>
        </body> 
    </html>
  );
}
